modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/SlimeKnights/TinkersMechworks/issues"
logoFile=""

[[mods]]
    modId="tmechworks"
    version="${version}"
    displayName="Tinkers' Mechworks"
    authors="Slime Knights"
    description='''

    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-mechworks"
    [[dependencies.tmechworks]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.tmechworks]]
        modId="mantle"
        mandatory=true
        versionRange="[1.4.29,)"